GET http://localhost:3000/clothes

###

GET http://localhost:3000/clothes/66150cf2fcc55f0a3ae5dc03

###

POST http://localhost:3000/clothes
Content-Type: application/json

{
    "name": "nom2",
    "brand": "brand",
    "price": 16,
    "type": "sweat"
}

###

DELETE http://localhost:3001/clothes/66150cf2fcc55f0a3ae5dc03

###
//Exclusivités (routes protégée)
GET http://localhost:3000/exclusivities


### Authentification

//Inscription
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email" : "test@example.com",
    "password": "superpass",
    "name": "testtfdfdf",
    "phoneNumber": "0600000000"
}

###

//Connexion

POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email" : "test@example.com",
    "password": "superpass"
}